import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {BrowserRouter,useNavigate,useLocation,Routes,Route,Navigate,Link} from 'react-router-dom'
import {Home,BookOpen,CalendarDays,UserRound,Stethoscope,LogOut,Menu,Leaf,Plus,ChevronRight,Clock,MapPin,CheckCircle2,Search,ArrowLeft,Users,BarChart3,FileText,Settings,AlertCircle} from 'lucide-react'
import './styles.css'
import {trainings,consultations,events,Training} from './data/mockData'
import {getStored,setStored} from './utils/storage'

type User={name:string;role:'produtor'|'apoio'}
const defaultUser:User={name:'João da Silva',role:'produtor'}

function App(){
 const [user,setUser]=useState<User|null>(()=>getStored('ss_user',null))
 const login=(role:'produtor'|'apoio')=>{const u=role==='apoio'?{name:'Mariana Costa',role}:{...defaultUser,role};setUser(u);setStored('ss_user',u)}
 const logout=()=>{localStorage.removeItem('ss_user');setUser(null)}
 return <BrowserRouter><Routes><Route path="/login" element={user?<Navigate to="/" replace/>:<Login onLogin={login}/>} /><Route path="*" element={user?<Shell user={user} onLogout={logout}/>:<Navigate to="/login" replace/>}/></Routes></BrowserRouter>
}

function Login({onLogin}:{onLogin:(r:'produtor'|'apoio')=>void}){
 const [mode,setMode]=useState<'login'|'cadastro'|'recuperar'|'codigo'>('login'); const [role,setRole]=useState<'produtor'|'apoio'>('produtor'); const nav=useNavigate();
 const submit=(e:React.FormEvent)=>{e.preventDefault(); if(mode==='recuperar'){setMode('codigo');return} if(mode==='codigo'){setMode('login');return} onLogin(role);nav('/')}
 return <div className="auth"><div className="auth-visual"><div className="brand big"><span className="brand-icon"><Leaf size={27}/></span>Semeando Saberes</div><div className="auth-copy"><span className="eyebrow">REDE DE APOIO AGROECOLÓGICO</span><h1>Conhecimento que<br/><em>transforma</em> o campo.</h1><p>Conectamos agricultores familiares a capacitações, consultorias e uma rede de especialistas.</p></div><div className="auth-leaf">🌱</div></div><div className="auth-panel"><div className="mobile-brand brand"><span className="brand-icon"><Leaf size={21}/></span>Semeando Saberes</div>{mode==='login'&&<><h2>Bem-vindo de volta!</h2><p className="muted">Acesse sua conta para continuar.</p><div className="role-tabs"><button className={role==='produtor'?'active':''} onClick={()=>setRole('produtor')}>Produtor</button><button className={role==='apoio'?'active':''} onClick={()=>setRole('apoio')}>Rede de Apoio</button></div><form onSubmit={submit}><Field label="E-mail" placeholder="seu@email.com" type="email"/><Field label="Senha" placeholder="••••••••" type="password"/><button className="btn primary full">Entrar</button></form><button className="text-btn" onClick={()=>setMode('recuperar')}>Esqueci minha senha</button><p className="auth-footer">Ainda não possui uma conta? <button onClick={()=>setMode('cadastro')}>Cadastre-se</button></p></>}{mode==='cadastro'&&<><Back onClick={()=>setMode('login')}/><h2>Crie sua conta</h2><p className="muted">Comece a fazer parte da rede de apoio.</p><form onSubmit={submit}><Field label="Nome completo" placeholder="Seu nome"/><Field label="E-mail" placeholder="seu@email.com" type="email"/><Field label="Senha" placeholder="Crie uma senha" type="password"/><button className="btn primary full">Criar conta</button></form></>}{mode==='recuperar'&&<><Back onClick={()=>setMode('login')}/><h2>Recuperar senha</h2><p className="muted">Informe seu e-mail para receber um código de acesso.</p><form onSubmit={submit}><Field label="E-mail" placeholder="seu@email.com" type="email"/><button className="btn primary full">Enviar código</button></form></>}{mode==='codigo'&&<><Back onClick={()=>setMode('recuperar')}/><h2>Validar código</h2><p className="muted">Digite o código enviado para seu e-mail.</p><Field label="Código de verificação" placeholder="000000"/><button className="btn primary full" onClick={()=>setMode('login')}>Validar código</button></>}</div></div>
}
const Field=({label,placeholder,type='text'}:{label:string;placeholder:string;type?:string})=><label className="field"><span>{label}</span><input type={type} placeholder={placeholder} required/></label>
const Back=({onClick}:{onClick:()=>void})=><button className="back" onClick={onClick}><ArrowLeft size={18}/> Voltar</button>

function Shell({user,onLogout}:{user:User;onLogout:()=>void}){
 const [open,setOpen]=useState(false); const loc=useLocation(); const nav=useNavigate(); const apoio=user.role==='apoio'
 const producerItems=[['/','Dashboard',Home],['/capacitacoes','Capacitações',BookOpen],['/consultorias','Consultorias',Stethoscope],['/treinamentos','Meus Treinamentos',BarChart3],['/agenda','Agenda',CalendarDays],['/perfil','Perfil',UserRound]] as const
 const supportItems=[['/','Dashboard',Home],['/nova-capacitacao','Criar Capacitação',Plus],['/nova-consultoria','Criar Consultoria',Stethoscope],['/agenda','Agenda',CalendarDays],['/perfil','Perfil',UserRound]] as const
 const items=apoio?supportItems:producerItems
 return <div className="app"><aside className={open?'sidebar open':'sidebar'}><div className="brand"><span className="brand-icon"><Leaf size={21}/></span><span>Semeando Saberes</span></div><div className="profile-mini"><div className="avatar">{user.name[0]}</div><div><strong>{user.name}</strong><small>{apoio?'Rede de Apoio':'Produtor Rural'}</small></div></div><nav>{items.map(([to,label,Icon])=><Link key={to} to={to} onClick={()=>setOpen(false)} className={loc.pathname===to?'nav-item active':'nav-item'}><Icon size={19}/><span>{label}</span></Link>)}</nav><button className="logout" onClick={onLogout}><LogOut size={18}/> Sair</button></aside><main className="main"><header className="topbar"><button className="menu" onClick={()=>setOpen(!open)}><Menu/></button><div className="crumb">Semeando Saberes <ChevronRight size={15}/> <span>{items.find(x=>x[0]===loc.pathname)?.[1]||'Dashboard'}</span></div><div className="top-actions"><span className="status-dot"/><span className="desktop-only">Sistema online</span><div className="avatar small">{user.name[0]}</div></div></header><div className="page"><Routes><Route path="/" element={apoio?<SupportDashboard/>:<Dashboard user={user}/>}/><Route path="/capacitacoes" element={<Capacitacoes/>}/><Route path="/capacitacoes/:id" element={<TrainingDetail/>}/><Route path="/consultorias" element={<Consultorias/>}/><Route path="/treinamentos" element={<Treinamentos/>}/><Route path="/agenda" element={<Agenda/>}/><Route path="/perfil" element={<Perfil user={user}/>}/><Route path="/nova-capacitacao" element={<NewTraining/>}/><Route path="/nova-consultoria" element={<NewConsultation/>}/><Route path="*" element={<Navigate to="/"/>}/></Routes></div></main></div>
}

function Dashboard({user}:{user:User}){return <><div className="hero"><div><span className="eyebrow">BOM DIA, {user.name.split(' ')[0].toUpperCase()} 👋</span><h1>Vamos cultivar novos<br/><em>conhecimentos.</em></h1><p>Confira suas atividades e próximos compromissos.</p></div><div className="hero-art">🌾</div></div><section className="section"><div className="section-title"><div><h2>Seu resumo</h2><p>Acompanhe seu progresso</p></div></div><div className="stats"><Stat icon={BookOpen} value="3" label="Capacitações ativas"/><Stat icon={CheckCircle2} value="72%" label="Progresso médio"/><Stat icon={CalendarDays} value="2" label="Próximos eventos"/><Stat icon={Stethoscope} value="1" label="Consultoria confirmada"/></div></section><section className="grid-2"><div className="panel"><div className="panel-head"><div><h3>Continue aprendendo</h3><p>Retome de onde parou</p></div><Link to="/treinamentos" className="link">Ver todos</Link></div><div className="progress-card"><div className="course-icon leaf-bg"><Leaf/></div><div className="grow"><strong>Manejo Agroecológico de Pragas</strong><small>Capacitação · 72% concluído</small><div className="progress"><i style={{width:'72%'}}/></div></div><span className="percent">72%</span></div></div><div className="panel"><div className="panel-head"><div><h3>Próximos eventos</h3><p>Não perca seus compromissos</p></div><Link to="/agenda" className="link">Agenda</Link></div>{events.slice(0,3).map(e=><Event key={e.day} {...e}/>)}</div></section></>}
function Stat({icon:Icon,value,label}:{icon:any;value:string;label:string}){return <div className="stat"><div className="stat-icon"><Icon size={20}/></div><div><strong>{value}</strong><span>{label}</span></div></div>}
function Event({day,month,title,type}:{day:number;month:string;title:string;type:string}){return <div className="event"><div className="date"><strong>{day}</strong><small>{month}</small></div><div className="grow"><strong>{title}</strong><small>{type} · 14:00</small></div><ChevronRight size={17} className="muted-icon"/></div>}

function Capacitacoes(){const [q,setQ]=useState('');const list=trainings.filter(t=>t.title.toLowerCase().includes(q.toLowerCase())||t.category.toLowerCase().includes(q.toLowerCase()));return <><PageTitle eyebrow="APRENDA E COMPARTILHE" title="Capacitações" subtitle="Conhecimento prático para fortalecer sua produção."/><div className="toolbar"><div className="search"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Buscar capacitação..."/></div><div className="filters"><button className="chip active">Todas</button><button className="chip">Produção</button><button className="chip">Gestão</button><button className="chip">Qualidade</button></div></div><div className="cards">{list.map(t=><TrainingCard key={t.id} t={t}/>)}</div></>}
function TrainingCard({t}:{t:Training}){return <Link className="training-card" to={`/capacitacoes/${t.id}`}><div className={`training-cover ${t.color}`}><BookOpen size={34}/><span>{t.category}</span></div><div className="card-body"><h3>{t.title}</h3><p>{t.description}</p><div className="meta"><span><CalendarDays size={15}/>{t.date}</span><span><Clock size={15}/>{t.time}</span></div><div className="card-bottom"><small>{t.enrolled}/{t.spots} inscritos</small><span className="link">Ver detalhes <ChevronRight size={15}/></span></div></div></Link>}
function TrainingDetail(){const id=Number(useLocation().pathname.split('/').pop());const t=trainings.find(x=>x.id===id)||trainings[0];const [done,setDone]=useState(false);return <><BackLink to="/capacitacoes" text="Voltar para capacitações"/><div className="detail"><div className={`detail-cover ${t.color}`}><BookOpen size={58}/><span>{t.category}</span></div><div className="detail-content"><span className="eyebrow">CAPACITAÇÃO</span><h1>{t.title}</h1><p className="lead">{t.description}</p><div className="detail-grid"><Info icon={UserRound} label="Instrutor" value={t.instructor}/><Info icon={CalendarDays} label="Data" value={`${t.date} · ${t.time}`}/><Info icon={MapPin} label="Local" value={t.location}/><Info icon={Users} label="Vagas" value={`${t.spots-t.enrolled} disponíveis`}/></div><div className="detail-actions">{done?<div className="success"><CheckCircle2/> Inscrição realizada!</div>:<button className="btn primary" onClick={()=>setDone(true)}>Inscrever-me na capacitação</button>}</div></div></div></>}
const Info=({icon:Icon,label,value}:{icon:any;label:string;value:string})=><div className="info"><Icon size={18}/><div><small>{label}</small><strong>{value}</strong></div></div>
const BackLink=({to,text}:{to:string;text:string})=><Link className="back" to={to}><ArrowLeft size={18}/>{text}</Link>

function Consultorias(){const [items,setItems]=useState(consultations);return <><PageTitle eyebrow="SUPORTE TÉCNICO" title="Consultorias" subtitle="Encontre apoio especializado para os desafios da sua propriedade."/><div className="notice"><Stethoscope/><div><strong>Precisa de ajuda no campo?</strong><span>Solicite uma consultoria e converse com um especialista da nossa rede.</span></div><button className="btn primary" onClick={()=>setItems([...items,{id:Date.now(),title:'Nova solicitação de consultoria',specialist:'Aguardando especialista',specialty:'A definir',date:'A combinar',time:'A combinar',status:'Solicitada',description:'Sua solicitação foi registrada e será analisada pela rede de apoio.'}])}>Solicitar consultoria</button></div><div className="section-title"><div><h2>Minhas solicitações</h2><p>Acompanhe o andamento dos atendimentos.</p></div></div><div className="consult-list">{items.map(c=><div className="consult-card" key={c.id}><div className="consult-icon"><Stethoscope/></div><div className="grow"><div className="row"><h3>{c.title}</h3><span className={`badge ${c.status==='Confirmada'?'ok':''}`}>{c.status}</span></div><p>{c.description}</p><div className="meta"><span><UserRound size={15}/>{c.specialist} · {c.specialty}</span><span><CalendarDays size={15}/>{c.date} · {c.time}</span></div></div><ChevronRight/></div>)}</div></>}

function Treinamentos(){return <><PageTitle eyebrow="MEU DESENVOLVIMENTO" title="Meus Treinamentos" subtitle="Acompanhe suas capacitações e evolução."/><div className="training-list">{trainings.slice(0,3).map(t=><div className="my-training" key={t.id}><div className="course-icon leaf-bg"><BookOpen/></div><div className="grow"><div className="row"><h3>{t.title}</h3><strong>{t.progress||0}%</strong></div><p>{t.instructor} · {t.date}</p><div className="progress"><i style={{width:`${t.progress||0}%`}}/></div><small>{t.progress===72?'Você está quase lá! Continue avançando.':'Continue o treinamento para concluir esta capacitação.'}</small></div></div>)}</div></>}
function Agenda(){return <><PageTitle eyebrow="SEUS COMPROMISSOS" title="Agenda" subtitle="Capacitações e consultorias em um só lugar."/><div className="agenda-layout"><div className="calendar"><div className="calendar-head"><button>‹</button><strong>Agosto 2026</strong><button>›</button></div><div className="weekdays">{['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=><span key={x}>{x}</span>)}</div><div className="days">{Array.from({length:42},(_,i)=>{const d=i-5;const has=events.some(e=>e.day===d);return <div className={d===16?'day today':''} key={i}>{d>0&&d<=31?<><span>{d}</span>{has&&<i/>}</>:null}</div>})}</div></div><div className="panel agenda-events"><div className="panel-head"><div><h3>Próximos eventos</h3><p>Agosto de 2026</p></div></div>{events.map(e=><Event key={e.day+e.title} {...e}/>)}</div></div></>}
function Perfil({user}:{user:User}){const [name,setName]=useState(user.name);const [saved,setSaved]=useState(false);return <><PageTitle eyebrow="MINHA CONTA" title="Perfil" subtitle="Gerencie seus dados pessoais e informações da propriedade."/><div className="profile-grid"><div className="panel profile-card"><div className="profile-large">{name[0]}</div><h2>{name}</h2><span>Produtor Rural</span><button className="btn secondary">Alterar foto</button></div><div className="panel form-panel"><div className="panel-head"><div><h3>Dados pessoais</h3><p>Atualize suas informações.</p></div></div><label className="field"><span>Nome completo</span><input value={name} onChange={e=>setName(e.target.value)}/></label><Field label="E-mail" placeholder="joao@email.com" type="email"/><Field label="Telefone" placeholder="(85) 99999-9999"/><div className="divider"/><h3>Dados da propriedade</h3><div className="form-grid"><Field label="Nome da propriedade" placeholder="Sítio Boa Esperança"/><Field label="Município" placeholder="Maracanaú - CE"/></div><button className="btn primary" onClick={()=>setSaved(true)}>{saved?'Dados salvos!':'Salvar alterações'}</button></div></div></>}

function SupportDashboard(){const [published,setPublished]=useState(false);return <><div className="hero support"><div><span className="eyebrow">REDE DE APOIO</span><h1>Transforme conhecimento<br/><em>em impacto.</em></h1><p>Gerencie suas capacitações e ofereça suporte aos produtores.</p></div><div className="hero-art">🤝</div></div><div className="stats"><Stat icon={BookOpen} value="12" label="Capacitações publicadas"/><Stat icon={Users} value="86" label="Produtores alcançados"/><Stat icon={Stethoscope} value="7" label="Consultorias ativas"/><Stat icon={BarChart3} value="94%" label="Avaliação média"/></div><section className="grid-2"><div className="panel"><div className="panel-head"><div><h3>Atalhos</h3><p>Publique novos conteúdos</p></div></div><div className="quick-actions"><Link to="/nova-capacitacao" className="quick"><Plus/><strong>Nova capacitação</strong><span>Crie um novo treinamento</span></Link><Link to="/nova-consultoria" className="quick"><Stethoscope/><strong>Nova consultoria</strong><span>Ofereça suporte técnico</span></Link></div></div><div className="panel"><div className="panel-head"><div><h3>Atividade recente</h3><p>Últimas interações</p></div></div><Event day={14} month="AGO" title="Inscrição em Manejo Agroecológico" type="Novo produtor"/><Event day={13} month="AGO" title="Consultoria solicitada" type="Aguardando atendimento"/></div></section>{published&&<div className="toast"><CheckCircle2/> Capacitação criada com sucesso!</div>}</>}
function NewTraining(){const [saved,setSaved]=useState(false);return <><BackLink to="/" text="Voltar ao dashboard"/><PageTitle eyebrow="REDE DE APOIO" title="Criar Capacitação" subtitle="Publique uma nova oportunidade de aprendizado para os produtores."/><div className="panel form-panel narrow"><Field label="Título da capacitação" placeholder="Ex.: Manejo Agroecológico de Pragas"/><div className="form-grid"><Field label="Categoria" placeholder="Produção"/><Field label="Instrutor" placeholder="Nome do especialista"/></div><div className="form-grid"><Field label="Data" placeholder="20/08/2026"/><Field label="Horário" placeholder="14:00"/></div><Field label="Local" placeholder="Centro comunitário ou Online"/><label className="field"><span>Descrição</span><textarea placeholder="Explique o que os participantes irão aprender..."/></label><div className="actions"><Link to="/" className="btn secondary">Cancelar</Link><button className="btn primary" onClick={()=>setSaved(true)}>Publicar capacitação</button></div>{saved&&<div className="inline-success"><CheckCircle2/> Capacitação publicada no MVP.</div>}</div></>}
function NewConsultation(){const [saved,setSaved]=useState(false);return <><BackLink to="/" text="Voltar ao dashboard"/><PageTitle eyebrow="REDE DE APOIO" title="Criar Consultoria" subtitle="Disponibilize um atendimento técnico para os produtores."/><div className="panel form-panel narrow"><Field label="Título da consultoria" placeholder="Ex.: Diagnóstico de pragas"/><div className="form-grid"><Field label="Especialidade" placeholder="Agronomia"/><Field label="Responsável" placeholder="Nome do especialista"/></div><div className="form-grid"><Field label="Data disponível" placeholder="21/08/2026"/><Field label="Horário" placeholder="10:00"/></div><label className="field"><span>Descrição do atendimento</span><textarea placeholder="Descreva o tipo de suporte oferecido..."/></label><div className="actions"><Link to="/" className="btn secondary">Cancelar</Link><button className="btn primary" onClick={()=>setSaved(true)}>Publicar disponibilidade</button></div>{saved&&<div className="inline-success"><CheckCircle2/> Consultoria disponibilizada no MVP.</div>}</div></>}
function PageTitle({eyebrow,title,subtitle}:{eyebrow:string;title:string;subtitle:string}){return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
